// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh36jwxbwABQVUzqZzZ3ko6Y8nmXzna8k',
    appId: '1:675704566308:web:250155d54a91051f8fdeb1',
    messagingSenderId: '675704566308',
    projectId: 'raise-hope-new',
    authDomain: 'raise-hope-new.firebaseapp.com',
    storageBucket: 'raise-hope-new.appspot.com',
    measurementId: 'G-SENT2JCE18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIyoclqow8b2XFI6wSclIMWeeZNl-qLLw',
    appId: '1:675704566308:android:1a2b278aa6d95c548fdeb1',
    messagingSenderId: '675704566308',
    projectId: 'raise-hope-new',
    storageBucket: 'raise-hope-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAbeUjYeDJvxlABdVwDXF_gm9j4SziU9A',
    appId: '1:675704566308:ios:b42d8cc15a0e65cd8fdeb1',
    messagingSenderId: '675704566308',
    projectId: 'raise-hope-new',
    storageBucket: 'raise-hope-new.appspot.com',
    iosBundleId: 'org.examApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAbeUjYeDJvxlABdVwDXF_gm9j4SziU9A',
    appId: '1:675704566308:ios:b42d8cc15a0e65cd8fdeb1',
    messagingSenderId: '675704566308',
    projectId: 'raise-hope-new',
    storageBucket: 'raise-hope-new.appspot.com',
    iosBundleId: 'org.examApp',
  );
}
